FROM node:20

#Set the working directory in the container
WORKDIR /usr/src/app

#Copy package.json and package-lock.json to the working directory
COPY package*.json ./

#Install app dependencies
RUN npm install

#Copy the rest of the application code to the working directory
COPY . .

#Expose the port your app runs on
EXPOSE 8080

#Command to run your application
CMD ["npm", "start"]